#!/usr/bin/env zsh
# This script is used in case the main bin/da_dev
# needs to be built.
# Once that is done, the binary can compile a new
# binary using: da_dev compile bin
#
#
set -u -e -o pipefail
cd "$( dirname "$(realpath "$0")" )/.."
echo "=== in $PWD" >&2
export SHARDS_INSTALL_PATH="$PWD/.shards/.install"
export CRYSTAL_PATH="/usr/lib/crystal:$PWD/.shards/.install"
crystal deps update
crystal deps prune
mkdir -p tmp/out
set -x
crystal build -o tmp/out/da_dev.tmp bin/__.cr
rm -f bin/da_dev
mv tmp/out/da_dev.tmp bin/da_dev
